#!/bin/sh
# shellcheck disable=SC1091,SC3060

if [ "$ACTION" = "add" ]; then
  [ "$DEVICENAME" = "$(uci get network.wan.device)" ] || exit 0

elif [ "$ACTION" = "ifup" ]; then
  [ "$DEVICE" = "$(uci get network.wan.device)" ] || exit 0

else
  exit 0

fi

if [ -x /etc/init.d/att-auth ] && /etc/init.d/att-auth enabled; then
  logger -t att-auth "Reloading due to $ACTION of $INTERFACE ($DEVICE)"
  /etc/init.d/att-auth restart
fi
